### PR TITLE
Docs: Clean up docs, fix mistakes

### PR DESCRIPTION
**Pull request by nikitavoloboev**

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Let me know what you think of the changes @yqrashawn, I tried to make the README more user friendly.

The markdown links have to be swapped to org mode, I couldn't do it as I am not familiar with it. I also think .org is not that good of a choice over a traditional .md file because much less people know what .org is. Which makes contributing harder.

**Comment by nikitavoloboev** [comment]
If you think this is appropriate and you can change the links or brush up the changes a bit yourself, you can merge this.

I will open a new PR later for clarifying and improving the tutorial too. 🙂

**Comment by nikitavoloboev** [comment]
Also I am not sure if my search and replace of `defination -> definition` broke something. As I saw it was used on code.

**Comment by yqrashawn** [comment]
Thanks!

**Pull request merged**
